### PR TITLE
Festure/sudoku resolver

### PR DESCRIPTION
**Pull request by jf423**
# Su Doku

## Libraries
- yarn v1.19.1
- node v10.15.3
- babel v7.11.4
- jest v26.4.2

## Install Dependencies
```
yarn install
```

## Get Started
```
yarn start
```
(Will run the Su Doku resolver and write the result to the answer.txt)

## Unit Test
```
yarn test
```

### CODE REVIEW

**Comment by jf423** [comment]
Hi @raymond4entrak ,

The Sudoku solver has been completed and the instruction is addressed in the above, thanks.

**Comment by raymond4entrak** [comment]
@jf423 your solution impresses me.  How do you get the link of this repo?

**Comment by jf423** [comment]
Hi @raymond4entrak 
I get this link from the headhunter - Debbie.

**Comment by raymond4entrak** [comment]
> Hi @raymond4entrak
> Thanks for the review.
> I get this link from the headhunter.
> Should I need to cancel my pull request?

It's ok.  Please notify your headhunter to forward your profile to me.  Thanks.

**Pull request closed without merging**
